AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Discogs Service

Resources:
  Discogs:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      CodeUri: ./dist/
      Runtime: nodejs6.10
      Timeout: 30
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
